kind: Pod
apiVersion: v1
metadata:
  name: test-app
  namespace: $NAMESPACE
  labels:
    app: test
spec:
  containers:
  - name: test-app
    image: hashicorp/http-echo
    args:
      - "-text=test"

---

kind: Service
apiVersion: v1
metadata:
  namespace: $NAMESPACE
  name: test-service
spec:
  selector:
    app: test
  ports:
    - port: 5678 # Default port for image

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: $NAMESPACE
  labels:
    name: test-ingress
spec:
  rules:
  - host: $HOST
    http:
      paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: test-service
              port: 
                number: 5678
---
